---
- name: Build repository details with port
  set_fact:
    registry_url: "{{ registry_protocol }}://{{ registry_server }}:{{ registry_port }}"
    repository_name: "{{ registry_server }}:{{ registry_port }}"
  when: registry_server is defined and registry_port is defined

- name: Build repository details without port
  set_fact:
    registry_url: "{{ registry_protocol }}://{{ registry_server }}"
    repository_name: "{{ registry_server }}"
  when: registry_server and registry_port is not defined

- name: Log into private registry
  docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
  when: registry_url is defined

# TODO: Change this to handle multiple private repos
